#!/bin/bash
# Definir variables para colores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetear colores
RESET='\033[0m'
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────   SlowDNS By E-SAN-VPN   ────────────── ${YELLOW}"
echo -e ""
echo -e "      สคริปต์นี้จะติดตั้ง"
echo -e "     ชะลอตัวสำหรับการสร้างช่องสัญญาณ DNS ด้วย "
echo -e ""
echo -e "         \033[1;33mSlowDNS By E-SAN-VPN \033[1;37m"
echo -e ""
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
echo ""
echo -e " กำลังกำหนดค่า iptables "
ipt_set () {
cd /etc
rm -rf rc.local
wget https://e-san-vpn.in.net/Install/slowdns/iptables/rc.local
chmod +x /etc/rc.local
IP=$(wget -qO- ipv4.e-san-vpn.in.net)
sed -i "1 a\iptables -t nat -A POSTROUTING -s 10.8.0.0/16 -j SNAT --to $IP" /etc/rc.local > /dev/null 2>&1
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ติดตั้งระบบ SlowDNS \033[1;33m"
echo ""
cd /etc/slowdns
echo -ne "\033[1;32m NS หรือ NameServer ของคุณ \033[1;37m: "; read nameserver
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://e-san-vpn.in.net/Install/slowdns/startdns 
wget https://e-san-vpn.in.net/Install/slowdns/restartdns
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo " กำลังตรวจสอบการมีอยู่ของคีย์ "
sleep 2
echo ""
echo "       โปรดรอ...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e " พบไฟล์คีย์ "
sleep 1
echo ""
key () {
echo " ต้องการที่จะสร้างคีย์ของคุณอย่างไร "
echo ""
echo "[ 1 ] | ใช้คีย์ที่มีอยู่ในไฟล์ "
echo "[ 2 ] | ลบไฟล์และสร้างรหัสใหม่ "
echo "[ 3 ] | ลบไฟล์และใช้คีย์ปัจจุบันของสคริปต์ "
echo "[ x ] | ยกเลิกการติดตั้ง "
echo ""
echo -ne "Enter an option: " && read option
case $option in
1) Option1 ;;
2) Option2 ;;
3) Option3 ;;
x) OptionX ;;
*) "Unknown command" ; echo ; key;;
esac
}
Option1 () {
echo -ne " กำลังกู้คืนคีย์ที่มีอยู่ " && sleep 2 && echo "OK!"
echo ""
echo -e " สำเร็จแล้ว "
finish_ist () {
cd
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS By E-SAN-VPN ──────────────── ${YELLOW}"
echo -e "${GREEN} การติดตั้งเสร็จสมบูรณ์ "
echo ""
echo -ne "${YELLOW} NameServer คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
echo -ne "${YELLOW} Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW} Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "${YELLOW} เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต ${YELLOW}"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
}
Option2 () {
cd
rm server.key server.pub
echo " กำลังสร้างคีย์ใหม่ "
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e " สำเร็จแล้ว "
finish_ist () {
cd
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
cd /etc/slowdns && ./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS By E-SAN-VPN ──────────────── ${YELLOW}"
echo -e "${GREEN} การติดตั้งเสร็จสมบูรณ์ "
echo ""
echo -ne "${YELLOW} NameServer คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
echo -ne "${YELLOW} Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW} Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "${YELLOW} เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต ${YELLOW}"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
slowdns
}
Option3 () {
echo -e " กำลังดาวน์โหลดคีย์เริ่มต้น "
cd
rm server.key server.pub
wget https://e-san-vpn.in.net/Install/slowdns/server.key > /dev/null 2>&1
wget https://e-san-vpn.in.net/Install/slowdns/server.pub > /dev/null 2>&1
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
sleep 1
echo -e " ดาวน์โหลดเสร็จสมบูรณ์ "
sleep 1
cd /etc/slowdns/
echo -e " สำเร็จแล้ว "
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS By E-SAN-VPN ──────────────── ${YELLOW}"
echo -e "${GREEN} การติดตั้งเสร็จสมบูรณ์ "
echo ""
echo -ne "${YELLOW} NameServer คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
echo -ne "${YELLOW} Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW} Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "${YELLOW} เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต ${YELLOW}"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
slowdns
}
OptionX () {
exit
}
key
else
echo -e "ไม่มีคีย์ในบันทึก"
echo ""
key_gen () {
echo " ต้องการที่จะสร้างคีย์ของคุณอย่างไร "
echo ""
echo "[ 1 ] | ใช้คีย์ปัจจุบันของสคริปต์ "
echo "[ 2 ] | สร้างคีย์ใหม่เมื่อติดตั้ง "
echo "[ x ] | ยกเลิกการติดตั้ง "
echo ""
echo -ne "Enter an option: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Unknown command" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo " กำลังสร้างคีย์ของคุณ "
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e " สำเร็จแล้ว "
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS By E-SAN-VPN ──────────────── ${YELLOW}"
echo -e "${GREEN} การติดตั้งเสร็จสมบูรณ์ "
echo ""
echo -ne "${YELLOW} NameServer คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
echo -ne "${YELLOW} Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW} Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "${YELLOW} เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต ${YELLOW}"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
slowdns
}
opc_key1 () {
echo -e " กำลังดาวน์โหลดคีย์เริ่มต้น "
cd
wget https://e-san-vpn.in.net/Install/slowdns/server.key > /dev/null 2>&1
wget https://e-san-vpn.in.net/Install/slowdns/server.pub > /dev/null 2>&1
sleep 1
echo -e " ดาวน์โหลดเสร็จสมบูรณ์ "
sleep 1
cd /etc/slowdns/
echo -e " สำเร็จแล้ว "
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m การติดตั้งเสร็จสมบูรณ์ \033[0m"
echo ""
echo -ne "\033[1;33m NameServer คือ :\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33m Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33m คำสั่ง Tremux คือ :\033[0m curl -sO https://e-san-vpn.in.net/Install/slowdns/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "\033[1;33m เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต \033[0m"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
}
opc_key2 () {
echo "Generating your key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant E-SAN
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ─────────────── SlowDNS By E-SAN-VPN ──────────────── ${YELLOW}"
echo -e "${GREEN} การติดตั้งเสร็จสมบูรณ์ "
echo ""
echo -ne "${YELLOW} NameServer คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
echo -ne "${YELLOW} Public KEY คือ :\033[0m " && cat /root/server.pub
echo ""
echo -e "${YELLOW} Public KEY ถูกบันทึกไว้ในไฟล์ /root/server.pub \033[0m"
echo -e "${YELLOW} เก็บไว้ในที่ปลอดภัย คุณอาจต้องการมันในอนาคต ${YELLOW}"
echo ""
read -p " กด [Enter] เพื่อกลับไปที่เมนูหรือ CTRL+C เพื่อออก "
slowdns
}
opc_keyx () {
echo " ยกเลิกการติดตั้ง "
sleep 2
exit
}
key_gen
fi
