#!/bin/bash
# Definir variables para colores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetear colores
RESET='\033[0m'
clear
slowdns () {
echo -e "${RED}────────────    E-SAN VPN    ──────────── ${YELLOW}"
    archivo="/root/server.pub"
    if [ -e "$archivo" ]; then
        echo -ne "${YELLOW}DNS คือ : ${WHITE} " && cat /etc/slowdns/infons
echo ""
        echo -ne "${YELLOW}Public KEY คือ :\033[0m " && cat /root/server.pub
    else
        echo "ยังไม่มีข้อมูลของระบบ"
    fi
echo -e "${RED}────────────    E-SAN VPN    ──────────── ${YELLOW}"
    echo -e "${YELLOW}[${GREEN}01${YELLOW}]${WHITE} | ติดตั้งระบบ SlowDNS "
    echo -e "${YELLOW}[${GREEN}02${YELLOW}]${WHITE} | ดูข้อมูล "
    echo -e "${YELLOW}[${GREEN}03${YELLOW}]${WHITE} | เปิดระบบ SlowDNS "
    echo -e "${YELLOW}[${GREEN}00${YELLOW}]${WHITE} | ออก"
    echo ""
    echo -ne "${YELLOW} Enter the number :\0033[m " && read option
    case $option in
    1|01) Option1 ;;
    2|02) Option2 ;;
    3|03) Option3 ;;
    0|00) Sair ;;
    *) "Invalid option" ; echo ; slowdns ;;
    esac
    }

Option1 () {
    clear
    bash /etc/slowdns/slowdns-install
}

Option2 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option3 () {
    clear
    bash /etc/slowdns/startdns
}

Sair() {
    clear
    cd
}
clear
slowdns
